### ISSUE TITLE
Improve wildcard option

### ISSUE THREAD

**Issue by crskycode** [A200K/IDA-Pro-SigMaker#10]
Sometimes we don't want to use wildcards for constant operands, because those bytes will not be affected by relocations.

```
.text:0043AE70 55                                      push    ebp
.text:0043AE71 8B EC                                   mov     ebp, esp
.text:0043AE73 F6 45 10 0F                             test    byte ptr [ebp+hModule], 0Fh
.text:0043AE77 74 04                                   jz      short loc_43AE7D
.text:0043AE79 33 C0                                   xor     eax, eax
.text:0043AE7B 5D                                      pop     ebp
.text:0043AE7C C3                                      retn
```

Output

```
Signature for 43AE70: 55 8B EC F6 45 ? ? 74
```

Thank you for developing this excellent plugin.

**Comment by A200K** [comment]
Thanks for your feedback and kind words!
To see if I got that correctly - the instruction at 43AE73 has two operands, a ptr and a constant. Now, you would like to have the "10"-Byte wildcarded, as it represents the "ebp+hModule" part (which can change), while you want the constant "0F"-Byte NOT wildcarded.

Did I get that right?

**Comment by crskycode** [comment]
In fact, ebp+hModule will not change. 10 0F are constant.

**Comment by A200K** [comment]
@crskycode I implemented an option to choose what kind of operands should be wildcarded. 
In your case, you probably want to only check "Direct Memory Reference":
![](https://i.imgur.com/4eW8oiJ.png)

**Comment by crskycode** [comment]
Thank you for implementing these improvements so quickly, awesome. 👍
