### ISSUE TITLE
IDA Pro 9.0 Has  been leaked.

### ISSUE THREAD

**Issue by Euarno** [A200K/IDA-Pro-SigMaker#14]
IDA Pro 9.0 Has  been leaked. Should we consider updating a branch for it? Someone has already implemented migration for SigMake https://github.com/TKazer/IDA-Pro-9.0-SigMaker

**Comment by A200K** [comment]
Yeah, there was already a pull request for adaption to IDA 9 SDK: https://github.com/A200K/IDA-Pro-SigMaker/pull/13
It‘s on a separate branch, because I wasn‘t able to check downwards compatibility yet
