### ISSUE TITLE
Ida 9.0.240925 can't load SigMaker

### ISSUE THREAD

**Issue by 0kolya0** [A200K/IDA-Pro-SigMaker#24]
Error Log:
LoadLibrary(C:\IDA\plugins\SigMaker9_64.dll)  error: module could not be found.
C:\IDA\plugins\SigMaker9_64.dll: can't load file

Hex-rays version 9.0.0.240925

**Comment by 0kolya0** [comment]
I fixed it by compiling it manually instead of downloading it from GitHub.

**Comment by papstuc** [comment]
This occurs due to idalib64.lib being removed in this version. When checking the precompiled version's IAT you'll see it needs ida64.dll, which is not loaded and thus it fails.

**Comment by stuttermess** [comment]
> I fixed it by compiling it manually instead of downloading it from GitHub.

by any chance, could you give it to me? i tried compiling it myself but i failed extremely.

**Comment by HongThatCong** [comment]
Try with this build
[SigMaker9.dll.gz](https://github.com/user-attachments/files/17742796/SigMaker9.dll.gz)
