### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RoccoZero** [A200K/IDA-Pro-SigMaker#8]
this is an error if the pattern is too long
![image](https://github.com/A200K/IDA-Pro-SigMaker/assets/33149580/18517341-e741-4ec1-af3a-82bae61324f7)

**Comment by A200K** [comment]
Would you mind posting the signature you tried?
I'm curious how long your signature must be to cause this error lol.
This should be easily fixable though

**Comment by A200K** [comment]
Can you try this and confirm the problem is solved? I increased the regex stack size a bit

[1.0.3.zip](https://github.com/user-attachments/files/16150389/1.0.3.zip)

**Comment by RoccoZero** [comment]
> Can you try this and confirm the problem is solved? I increased the regex stack size a bit
> 
> [1.0.3.zip](https://github.com/user-attachments/files/16150389/1.0.3.zip)

yes fixed

**Comment by RoccoZero** [comment]
We could improve this window a little so that it displays more. thanks in advance

<img width="1235" alt="image" src="https://github.com/A200K/IDA-Pro-SigMaker/assets/33149580/37f42d60-f6da-4756-a8b6-a59ad4ca7ebc">

**Comment by A200K** [comment]
> We could improve this window a little so that it displays more. thanks in advance

I use the IDA API function "ask_str" to create a window for string input, I don't have any control over the window behaviour:
https://hex-rays.com/products/ida/support/idadoc/288.shtml

Implementing a whole custom window handler just for that is a bit overkill in my opinion. I'll see if there would be any other benefits of doing so.

Thanks for your feedback!
